//! Engine-computed parametric masks.
//!
//! Evaluated against the *input* image (before any ops) so they stay stable as
//! the user tweaks other sliders. Host bitmaps (segmentation, invert) still
//! win when supplied for the same id.

use serde::Deserialize;
use serde_json::Value;

use crate::ops::util::{hue_distance, luma, rgb_to_hsl, smoothstep};
use crate::{EngineError, ImageBuf, MaskBuf};

#[derive(Debug, Clone)]
pub enum MaskSource {
    /// Host-supplied bitmap (segmentation, invert, or unspecified).
    Host,
    LuminanceRange(LuminanceRangeParams),
    ColorRange(ColorRangeParams),
    LinearGradient(LinearGradientParams),
    RadialGradient(RadialGradientParams),
}

impl MaskSource {
    pub fn is_parametric(&self) -> bool {
        !matches!(self, MaskSource::Host)
    }

    pub fn parse(source: Option<&str>, params: &Value) -> Result<Self, EngineError> {
        let Some(name) = source else {
            return Ok(MaskSource::Host);
        };
        match name {
            "segmentation" | "invert" | "" => Ok(MaskSource::Host),
            "luminance_range" => Ok(MaskSource::LuminanceRange(parse_params(
                name,
                params,
            )?)),
            "color_range" => Ok(MaskSource::ColorRange(parse_params(name, params)?)),
            "linear_gradient" => Ok(MaskSource::LinearGradient(parse_params(name, params)?)),
            "radial_gradient" => Ok(MaskSource::RadialGradient(parse_params(name, params)?)),
            other => Err(EngineError::InvalidPipeline(format!(
                "unknown mask source \"{other}\""
            ))),
        }
    }

    pub fn generate(&self, image: &ImageBuf) -> Result<MaskBuf, EngineError> {
        match self {
            MaskSource::Host => Err(EngineError::InvalidPipeline(
                "host mask source cannot be generated by the engine".into(),
            )),
            MaskSource::LuminanceRange(p) => Ok(luminance_range(image, p)),
            MaskSource::ColorRange(p) => Ok(color_range(image, p)),
            MaskSource::LinearGradient(p) => Ok(linear_gradient(image, p)),
            MaskSource::RadialGradient(p) => Ok(radial_gradient(image, p)),
        }
    }
}

fn parse_params<T: Default + for<'de> Deserialize<'de>>(
    source: &str,
    params: &Value,
) -> Result<T, EngineError> {
    if params.is_null() {
        return Ok(T::default());
    }
    serde_json::from_value(params.clone()).map_err(|e| {
        EngineError::InvalidPipeline(format!("bad params for mask source \"{source}\": {e}"))
    })
}

#[derive(Debug, Clone, Deserialize)]
#[serde(default, deny_unknown_fields)]
pub struct LuminanceRangeParams {
    /// Inclusive luma floor (0..1).
    pub min: f32,
    /// Inclusive luma ceiling (0..1).
    pub max: f32,
    /// Soft falloff as a fraction of the image luma range (0..1). Default 0.1.
    pub softness: f32,
}

impl Default for LuminanceRangeParams {
    fn default() -> Self {
        Self {
            min: 0.0,
            max: 1.0,
            softness: 0.1,
        }
    }
}

#[derive(Debug, Clone, Deserialize)]
#[serde(default, deny_unknown_fields)]
pub struct ColorRangeParams {
    /// Target hue in degrees (0..360).
    pub hue: f32,
    /// Full-inclusion half-width in degrees. Default 25.
    pub range: f32,
    /// Extra falloff as a fraction of `range`. Default 0.4.
    pub softness: f32,
    /// Minimum saturation; near-grays below this are excluded. Default 0.08.
    #[serde(rename = "satMin", alias = "sat_min")]
    pub sat_min: f32,
    #[serde(rename = "lumMin", alias = "lum_min")]
    pub lum_min: f32,
    #[serde(rename = "lumMax", alias = "lum_max")]
    pub lum_max: f32,
}

impl Default for ColorRangeParams {
    fn default() -> Self {
        Self {
            hue: 120.0,
            range: 25.0,
            softness: 0.4,
            sat_min: 0.08,
            lum_min: 0.0,
            lum_max: 1.0,
        }
    }
}

#[derive(Debug, Clone, Deserialize)]
#[serde(default, deny_unknown_fields)]
pub struct LinearGradientParams {
    pub x0: f32,
    pub y0: f32,
    pub x1: f32,
    pub y1: f32,
}

impl Default for LinearGradientParams {
    fn default() -> Self {
        // Top of the frame (1) fading to the bottom (0).
        Self {
            x0: 0.5,
            y0: 0.0,
            x1: 0.5,
            y1: 1.0,
        }
    }
}

#[derive(Debug, Clone, Deserialize)]
#[serde(default, deny_unknown_fields)]
pub struct RadialGradientParams {
    pub cx: f32,
    pub cy: f32,
    #[serde(rename = "radiusX", alias = "radius_x")]
    pub radius_x: f32,
    #[serde(rename = "radiusY", alias = "radius_y")]
    pub radius_y: f32,
    pub softness: f32,
}

impl Default for RadialGradientParams {
    fn default() -> Self {
        Self {
            cx: 0.5,
            cy: 0.5,
            radius_x: 0.4,
            radius_y: 0.4,
            softness: 0.3,
        }
    }
}

fn luminance_range(image: &ImageBuf, params: &LuminanceRangeParams) -> MaskBuf {
    let min = params.min.clamp(0.0, 1.0).min(params.max.clamp(0.0, 1.0));
    let max = params.max.clamp(0.0, 1.0).max(min);
    let softness = params.softness.clamp(0.0, 1.0);
    let falloff = softness.max(1e-4);
    let mut data = vec![0.0f32; (image.width * image.height) as usize];
    for (i, px) in image.data.chunks_exact(4).enumerate() {
        let l = luma(px[0], px[1], px[2]).clamp(0.0, 1.0);
        let into = smoothstep(min - falloff, min, l);
        let outof = 1.0 - smoothstep(max, max + falloff, l);
        data[i] = (into * outof).clamp(0.0, 1.0);
    }
    MaskBuf {
        width: image.width,
        height: image.height,
        data,
    }
}

fn color_range(image: &ImageBuf, params: &ColorRangeParams) -> MaskBuf {
    let hue = ((params.hue % 360.0) + 360.0) % 360.0;
    let range = params.range.clamp(0.5, 180.0);
    let softness = params.softness.clamp(0.0, 2.0);
    let falloff = (range * softness).max(0.5);
    let sat_min = params.sat_min.clamp(0.0, 1.0);
    let lum_min = params.lum_min.clamp(0.0, 1.0);
    let lum_max = params.lum_max.clamp(0.0, 1.0).max(lum_min);
    let mut data = vec![0.0f32; (image.width * image.height) as usize];
    for (i, px) in image.data.chunks_exact(4).enumerate() {
        let (h, s, l) = rgb_to_hsl(px[0], px[1], px[2]);
        let d = hue_distance(h, hue);
        let hue_w = 1.0 - smoothstep(range, range + falloff, d);
        let sat_w = if sat_min <= 0.0 {
            1.0
        } else {
            smoothstep(sat_min * 0.5, sat_min, s)
        };
        let lum_lo = if lum_min <= 0.0 {
            1.0
        } else {
            smoothstep((lum_min - 0.05).max(0.0), lum_min, l)
        };
        let lum_hi = if lum_max >= 1.0 {
            1.0
        } else {
            1.0 - smoothstep(lum_max, (lum_max + 0.05).min(1.0), l)
        };
        data[i] = (hue_w * sat_w * lum_lo * lum_hi).clamp(0.0, 1.0);
    }
    MaskBuf {
        width: image.width,
        height: image.height,
        data,
    }
}

fn linear_gradient(image: &ImageBuf, params: &LinearGradientParams) -> MaskBuf {
    let w = image.width as f32;
    let h = image.height as f32;
    let x0 = params.x0;
    let y0 = params.y0;
    let x1 = params.x1;
    let y1 = params.y1;
    let dx = x1 - x0;
    let dy = y1 - y0;
    let len2 = dx * dx + dy * dy;
    let mut data = vec![0.0f32; (image.width * image.height) as usize];
    if len2 < 1e-8 {
        data.fill(1.0);
        return MaskBuf {
            width: image.width,
            height: image.height,
            data,
        };
    }
    for y in 0..image.height {
        for x in 0..image.width {
            let px = (x as f32 + 0.5) / w;
            let py = (y as f32 + 0.5) / h;
            let t = ((px - x0) * dx + (py - y0) * dy) / len2;
            data[(y * image.width + x) as usize] = (1.0 - t.clamp(0.0, 1.0)).clamp(0.0, 1.0);
        }
    }
    MaskBuf {
        width: image.width,
        height: image.height,
        data,
    }
}

fn radial_gradient(image: &ImageBuf, params: &RadialGradientParams) -> MaskBuf {
    let w = image.width as f32;
    let h = image.height as f32;
    let rx = params.radius_x.abs().max(1e-4);
    let ry = params.radius_y.abs().max(1e-4);
    let softness = params.softness.clamp(0.0, 1.0);
    let inner = (1.0 - softness).clamp(0.0, 1.0);
    let mut data = vec![0.0f32; (image.width * image.height) as usize];
    for y in 0..image.height {
        for x in 0..image.width {
            let px = (x as f32 + 0.5) / w;
            let py = (y as f32 + 0.5) / h;
            let nx = (px - params.cx) / rx;
            let ny = (py - params.cy) / ry;
            let d = (nx * nx + ny * ny).sqrt();
            data[(y * image.width + x) as usize] = (1.0 - smoothstep(inner, 1.0, d)).clamp(0.0, 1.0);
        }
    }
    MaskBuf {
        width: image.width,
        height: image.height,
        data,
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn gray(width: u32, height: u32, value: f32) -> ImageBuf {
        let mut data = Vec::with_capacity((width * height * 4) as usize);
        for _ in 0..width * height {
            data.extend_from_slice(&[value, value, value, 1.0]);
        }
        ImageBuf {
            width,
            height,
            data,
        }
    }

    #[test]
    fn luminance_selects_bright_pixels() {
        let mut data = vec![0.1, 0.1, 0.1, 1.0, 0.9, 0.9, 0.9, 1.0];
        let img = ImageBuf {
            width: 2,
            height: 1,
            data: std::mem::take(&mut data),
        };
        let mask = luminance_range(
            &img,
            &LuminanceRangeParams {
                min: 0.6,
                max: 1.0,
                softness: 0.05,
            },
        );
        assert!(mask.data[0] < 0.05);
        assert!(mask.data[1] > 0.95);
    }

    #[test]
    fn linear_gradient_is_one_at_start() {
        let img = gray(8, 1, 0.5);
        let mask = linear_gradient(
            &img,
            &LinearGradientParams {
                x0: 0.0,
                y0: 0.0,
                x1: 1.0,
                y1: 0.0,
            },
        );
        assert!(mask.data[0] > 0.9);
        assert!(mask.data[7] < 0.1);
    }

    #[test]
    fn radial_is_one_at_center() {
        let img = gray(5, 5, 0.5);
        let mask = radial_gradient(&img, &RadialGradientParams::default());
        assert!(mask.data[12] > 0.9, "center should be inside, got {}", mask.data[12]);
        assert!(mask.data[0] < 0.2, "corner should fall off, got {}", mask.data[0]);
    }

    #[test]
    fn color_range_picks_green_not_red() {
        let img = ImageBuf {
            width: 2,
            height: 1,
            data: vec![0.1, 0.8, 0.1, 1.0, 0.8, 0.1, 0.1, 1.0],
        };
        let mask = color_range(
            &img,
            &ColorRangeParams {
                hue: 120.0,
                range: 25.0,
                softness: 0.3,
                sat_min: 0.1,
                lum_min: 0.0,
                lum_max: 1.0,
            },
        );
        assert!(mask.data[0] > 0.8, "green pixel, got {}", mask.data[0]);
        assert!(mask.data[1] < 0.2, "red pixel, got {}", mask.data[1]);
    }
}
