//! Declarative pipeline format (versions 1 to 4).
//!
//! ```json
//! {
//!   "version": 4,
//!   "masks": [
//!     { "id": "dress", "source": "segmentation", "prompt": "the red dress", "feather": 0.02 },
//!     { "id": "highlights", "source": "luminance_range", "params": { "min": 0.7, "max": 1.0 } }
//!   ],
//!   "operations": [
//!     { "op": "saturation", "params": { "amount": 0.4 }, "mask": "dress" }
//!   ]
//! }
//! ```
//!
//! `params` is optional on every operation; missing parameters fall back to
//! documented defaults. Unknown `op` names are a hard error so that typos in
//! AI- or human-authored pipelines never silently no-op.
//!
//! Version 2 adds optional per-op `mask` / `invertMask` / `maskStrength`.
//! Host bitmaps (segmentation) are supplied at apply time — the engine never
//! runs a model. Version 4 adds engine-computed parametric mask sources
//! (luminance range, color range, linear/radial gradients) evaluated against
//! the input image before any ops.
//!
//! Version 3 adds the optional top-level `frame` (non-destructive rotate +
//! crop). The frame is applied *after* every operation, so ops and masks work
//! in original image space; the crop rectangle is normalized to the rotated
//! frame. It is the only stage that changes image dimensions.

use std::collections::HashMap;

use serde::Deserialize;
use serde_json::Value;

use crate::frame::{CropRect, Frame, Rotation};
use crate::mask::{blend_masked, MaskBuf};
use crate::mask_sources::MaskSource;
use crate::ops;
use crate::{EngineError, ImageBuf};

pub const MIN_SUPPORTED_VERSION: u32 = 1;
pub const MAX_SUPPORTED_VERSION: u32 = 4;

#[derive(Debug, Deserialize)]
struct RawPipeline {
    #[serde(default = "default_version")]
    version: u32,
    #[serde(default)]
    masks: Vec<RawMaskDecl>,
    #[serde(default)]
    operations: Vec<RawOperation>,
    #[serde(default)]
    frame: Option<RawFrame>,
}

#[derive(Debug, Deserialize)]
#[serde(deny_unknown_fields)]
struct RawFrame {
    #[serde(default)]
    rotate: Option<u32>,
    #[serde(default)]
    crop: Option<RawCrop>,
}

#[derive(Debug, Deserialize)]
#[serde(deny_unknown_fields)]
struct RawCrop {
    x: f32,
    y: f32,
    width: f32,
    height: f32,
}

fn default_version() -> u32 {
    MIN_SUPPORTED_VERSION
}

#[derive(Debug, Deserialize)]
struct RawMaskDecl {
    id: String,
    #[serde(default)]
    #[allow(dead_code)]
    source: Option<String>,
    #[serde(default)]
    #[allow(dead_code)]
    prompt: Option<String>,
    #[serde(default)]
    feather: Option<f32>,
    #[serde(default)]
    params: Value,
}

#[derive(Debug, Deserialize)]
struct RawOperation {
    op: String,
    #[serde(default)]
    params: Value,
    #[serde(default)]
    mask: Option<String>,
    #[serde(default, rename = "invertMask")]
    invert_mask: Option<bool>,
    #[serde(default, rename = "maskStrength")]
    mask_strength: Option<f32>,
}

/// Host-declared mask metadata. Parametric sources are generated by the engine
/// from the input image when the host does not supply a bitmap for `id`.
#[derive(Debug, Clone)]
pub struct MaskDecl {
    pub id: String,
    pub feather: f32,
    pub source: MaskSource,
}

impl MaskDecl {
    /// Parse a single mask declaration (used by the WASM `render_mask` preview path).
    pub fn from_json(json: &str) -> Result<Self, EngineError> {
        let raw: RawMaskDecl = serde_json::from_str(json)
            .map_err(|e| EngineError::InvalidPipeline(e.to_string()))?;
        if raw.id.is_empty() {
            return Err(EngineError::InvalidPipeline(
                "mask id must not be empty".into(),
            ));
        }
        Ok(Self {
            id: raw.id,
            feather: raw.feather.unwrap_or(0.0).clamp(0.0, 1.0),
            source: MaskSource::parse(raw.source.as_deref(), &raw.params)?,
        })
    }

    pub fn render(&self, image: &ImageBuf) -> Result<MaskBuf, EngineError> {
        if !self.source.is_parametric() {
            return Err(EngineError::InvalidPipeline(format!(
                "mask \"{}\" is not a parametric source",
                self.id
            )));
        }
        let mut mask = self.source.generate(image)?;
        if self.feather > 0.0 {
            mask.feather(self.feather);
        }
        Ok(mask)
    }
}

/// A parsed, validated pipeline ready to run.
#[derive(Debug)]
pub struct Pipeline {
    operations: Vec<BoundOp>,
    mask_decls: Vec<MaskDecl>,
    frame: Frame,
}

#[derive(Debug)]
struct BoundOp {
    op: Operation,
    mask: Option<String>,
    invert_mask: bool,
    /// 0..1; scales the mask before invert. Only meaningful when `mask` is set.
    mask_strength: f32,
}

#[derive(Debug)]
pub enum Operation {
    Exposure(ops::exposure::Params),
    Contrast(ops::contrast::Params),
    ShadowsHighlights(ops::shadows_highlights::Params),
    ToneCurve(ops::tone_curve::Params),
    BlacksWhites(ops::blacks_whites::Params),
    DodgeBurn(ops::dodge_burn::Params),
    Saturation(ops::saturation::Params),
    ColorBalance(ops::color_balance::Params),
    ColorShift(ops::color_shift::Params),
    HslMixer(ops::hsl_mixer::Params),
    Grain(ops::grain::Params),
    FilmSoftness(ops::film_softness::Params),
    Vignette(ops::vignette::Params),
    Bloom(ops::bloom::Params),
    Halation(ops::halation::Params),
    LensBlur(ops::lens_blur::Params),
}

fn parse_params<T: Default + for<'de> Deserialize<'de>>(
    op: &str,
    params: Value,
) -> Result<T, EngineError> {
    if params.is_null() {
        return Ok(T::default());
    }
    serde_json::from_value(params)
        .map_err(|e| EngineError::InvalidPipeline(format!("bad params for \"{op}\": {e}")))
}

impl Pipeline {
    pub fn from_json(json: &str) -> Result<Self, EngineError> {
        let raw: RawPipeline = serde_json::from_str(json)
            .map_err(|e| EngineError::InvalidPipeline(e.to_string()))?;
        if raw.version < MIN_SUPPORTED_VERSION || raw.version > MAX_SUPPORTED_VERSION {
            return Err(EngineError::UnsupportedVersion(raw.version));
        }

        let mut mask_decls = Vec::with_capacity(raw.masks.len());
        for m in raw.masks {
            if m.id.is_empty() {
                return Err(EngineError::InvalidPipeline(
                    "mask id must not be empty".into(),
                ));
            }
            mask_decls.push(MaskDecl {
                id: m.id,
                feather: m.feather.unwrap_or(0.0).clamp(0.0, 1.0),
                source: MaskSource::parse(m.source.as_deref(), &m.params)?,
            });
        }

        let mut operations = Vec::with_capacity(raw.operations.len());
        for raw_op in raw.operations {
            let name = raw_op.op.as_str();
            let op = match name {
                "exposure" => Operation::Exposure(parse_params(name, raw_op.params)?),
                "contrast" => Operation::Contrast(parse_params(name, raw_op.params)?),
                "shadows_highlights" => {
                    Operation::ShadowsHighlights(parse_params(name, raw_op.params)?)
                }
                "tone_curve" => Operation::ToneCurve(parse_params(name, raw_op.params)?),
                "blacks_whites" => Operation::BlacksWhites(parse_params(name, raw_op.params)?),
                "dodge_burn" => Operation::DodgeBurn(parse_params(name, raw_op.params)?),
                "saturation" => Operation::Saturation(parse_params(name, raw_op.params)?),
                "color_balance" => Operation::ColorBalance(parse_params(name, raw_op.params)?),
                "color_shift" => Operation::ColorShift(parse_params(name, raw_op.params)?),
                "hsl_mixer" => Operation::HslMixer(parse_params(name, raw_op.params)?),
                "grain" => Operation::Grain(parse_params(name, raw_op.params)?),
                "film_softness" => Operation::FilmSoftness(parse_params(name, raw_op.params)?),
                "vignette" => Operation::Vignette(parse_params(name, raw_op.params)?),
                "bloom" => Operation::Bloom(parse_params(name, raw_op.params)?),
                "halation" => Operation::Halation(parse_params(name, raw_op.params)?),
                "lens_blur" => Operation::LensBlur(parse_params(name, raw_op.params)?),
                other => return Err(EngineError::UnknownOperation(other.to_string())),
            };

            if let Some(ref mask_id) = raw_op.mask {
                if mask_id.is_empty() {
                    return Err(EngineError::InvalidPipeline(
                        "operation mask id must not be empty".into(),
                    ));
                }
            }

            if raw_op.mask_strength.is_some() && raw_op.mask.is_none() {
                return Err(EngineError::InvalidPipeline(
                    "maskStrength requires a mask id".into(),
                ));
            }
            let mask_strength = raw_op.mask_strength.unwrap_or(1.0).clamp(0.0, 1.0);

            operations.push(BoundOp {
                op,
                mask: raw_op.mask,
                invert_mask: raw_op.invert_mask.unwrap_or(false),
                mask_strength,
            });
        }
        let frame = match raw.frame {
            None => Frame::default(),
            Some(raw_frame) => {
                let rotation = match raw_frame.rotate {
                    None => Rotation::R0,
                    Some(degrees) => Rotation::from_degrees(degrees)?,
                };
                let crop = match raw_frame.crop {
                    None => None,
                    Some(c) => Some(CropRect::validated(c.x, c.y, c.width, c.height)?),
                };
                Frame { rotation, crop }
            }
        };

        Ok(Self {
            operations,
            mask_decls,
            frame,
        })
    }

    /// The non-destructive frame transform (identity when absent).
    pub fn frame(&self) -> &Frame {
        &self.frame
    }

    /// Apply the frame transform to an already-processed image, producing the
    /// final (possibly differently-sized) output.
    pub fn apply_frame(&self, image: ImageBuf) -> ImageBuf {
        if self.frame.is_noop() {
            image
        } else {
            self.frame.apply(image)
        }
    }

    /// Apply the pipeline. `masks` maps declaration ids to bitmaps from the host.
    pub fn apply(
        &self,
        image: &mut ImageBuf,
        masks: Option<&HashMap<String, MaskBuf>>,
    ) -> Result<(), EngineError> {
        let prepared = self.prepare_masks(image, masks)?;

        for bound in &self.operations {
            match &bound.mask {
                None => self.apply_op(image, &bound.op),
                Some(mask_id) => {
                    let mask = prepared.get(mask_id).ok_or_else(|| {
                        EngineError::UnknownMask(mask_id.clone())
                    })?;
                    let mut edited = ImageBuf {
                        width: image.width,
                        height: image.height,
                        data: image.data.clone(),
                    };
                    self.apply_op(&mut edited, &bound.op);
                    *image = blend_masked(
                        image,
                        &edited,
                        mask,
                        bound.invert_mask,
                        bound.mask_strength,
                    );
                }
            }
        }
        Ok(())
    }

    fn prepare_masks(
        &self,
        image: &ImageBuf,
        masks: Option<&HashMap<String, MaskBuf>>,
    ) -> Result<HashMap<String, MaskBuf>, EngineError> {
        let empty = HashMap::new();
        let source = masks.unwrap_or(&empty);
        let mut prepared: HashMap<String, MaskBuf> = HashMap::new();
        let width = image.width;
        let height = image.height;

        for decl in &self.mask_decls {
            if let Some(mask) = source.get(&decl.id) {
                mask.ensure_size(width, height)?;
                let mut owned = mask.clone();
                if decl.feather > 0.0 {
                    owned.feather(decl.feather);
                }
                prepared.insert(decl.id.clone(), owned);
                continue;
            }
            if decl.source.is_parametric() {
                let mut owned = decl.source.generate(image)?;
                owned.ensure_size(width, height)?;
                if decl.feather > 0.0 {
                    owned.feather(decl.feather);
                }
                prepared.insert(decl.id.clone(), owned);
            }
        }

        // Ops may reference masks not listed in masks[] — still require the bitmap.
        for bound in &self.operations {
            if let Some(id) = &bound.mask {
                if prepared.contains_key(id) {
                    continue;
                }
                let mask = source.get(id).ok_or_else(|| EngineError::UnknownMask(id.clone()))?;
                mask.ensure_size(width, height)?;
                prepared.insert(id.clone(), mask.clone());
            }
        }

        Ok(prepared)
    }

    fn apply_op(&self, image: &mut ImageBuf, op: &Operation) {
        match op {
            Operation::Exposure(p) => ops::exposure::apply(image, p),
            Operation::Contrast(p) => ops::contrast::apply(image, p),
            Operation::ShadowsHighlights(p) => ops::shadows_highlights::apply(image, p),
            Operation::ToneCurve(p) => ops::tone_curve::apply(image, p),
            Operation::BlacksWhites(p) => ops::blacks_whites::apply(image, p),
            Operation::DodgeBurn(p) => ops::dodge_burn::apply(image, p),
            Operation::Saturation(p) => ops::saturation::apply(image, p),
            Operation::ColorBalance(p) => ops::color_balance::apply(image, p),
            Operation::ColorShift(p) => ops::color_shift::apply(image, p),
            Operation::HslMixer(p) => ops::hsl_mixer::apply(image, p),
            Operation::Grain(p) => ops::grain::apply(image, p),
            Operation::FilmSoftness(p) => ops::film_softness::apply(image, p),
            Operation::Vignette(p) => ops::vignette::apply(image, p),
            Operation::Bloom(p) => ops::bloom::apply(image, p),
            Operation::Halation(p) => ops::halation::apply(image, p),
            Operation::LensBlur(p) => ops::lens_blur::apply(image, p),
        }
    }

    pub fn len(&self) -> usize {
        self.operations.len()
    }

    pub fn is_empty(&self) -> bool {
        self.operations.is_empty()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn parses_full_pipeline() {
        let json = r#"{
            "version": 1,
            "operations": [
                { "op": "grain", "params": { "amount": 0.65, "size": 1.8 } },
                { "op": "tone_curve", "params": { "preset": "soft" } },
                { "op": "halation", "params": { "strength": 0.25 } }
            ]
        }"#;
        let p = Pipeline::from_json(json).unwrap();
        assert_eq!(p.len(), 3);
    }

    #[test]
    fn parses_version_two_with_masks() {
        let json = r#"{
            "version": 2,
            "masks": [{ "id": "dress", "prompt": "the red dress", "feather": 0.02 }],
            "operations": [
                { "op": "saturation", "params": { "amount": 0.4 }, "mask": "dress" },
                { "op": "exposure", "params": { "amount": -0.2 }, "mask": "dress", "invertMask": true }
            ]
        }"#;
        let p = Pipeline::from_json(json).unwrap();
        assert_eq!(p.len(), 2);
        assert_eq!(p.mask_decls.len(), 1);
    }

    #[test]
    fn parses_version_three_with_frame() {
        let json = r#"{
            "version": 3,
            "operations": [{ "op": "exposure", "params": { "amount": 0.2 } }],
            "frame": {
                "rotate": 90,
                "crop": { "x": 0.1, "y": 0.2, "width": 0.5, "height": 0.4 }
            }
        }"#;
        let p = Pipeline::from_json(json).unwrap();
        assert_eq!(p.len(), 1);
        assert_eq!(p.frame().rotation, Rotation::R90);
        let crop = p.frame().crop.unwrap();
        assert!((crop.x - 0.1).abs() < 1e-6);
        assert!((crop.height - 0.4).abs() < 1e-6);
    }

    #[test]
    fn frame_defaults_to_identity() {
        let p = Pipeline::from_json(r#"{"version":3,"operations":[]}"#).unwrap();
        assert!(p.frame().is_noop());
        let partial =
            Pipeline::from_json(r#"{"version":3,"operations":[],"frame":{"rotate":180}}"#).unwrap();
        assert_eq!(partial.frame().rotation, Rotation::R180);
        assert!(partial.frame().crop.is_none());
    }

    #[test]
    fn frame_rejects_unknown_fields_and_bad_rotation() {
        assert!(Pipeline::from_json(
            r#"{"version":3,"operations":[],"frame":{"rotate":45}}"#
        )
        .is_err());
        assert!(Pipeline::from_json(
            r#"{"version":3,"operations":[],"frame":{"zoom":2}}"#
        )
        .is_err());
        assert!(Pipeline::from_json(
            r#"{"version":3,"operations":[],"frame":{"crop":{"x":0,"y":0,"width":0.5}}}"#
        )
        .is_err());
    }

    #[test]
    fn params_are_optional() {
        let p = Pipeline::from_json(r#"{"version":1,"operations":[{"op":"blacks_whites"}]}"#).unwrap();
        assert_eq!(p.len(), 1);
    }

    #[test]
    fn version_defaults_to_one() {
        let p = Pipeline::from_json(r#"{"operations":[]}"#).unwrap();
        assert!(p.is_empty());
    }

    #[test]
    fn unknown_op_is_an_error() {
        let err = Pipeline::from_json(r#"{"version":1,"operations":[{"op":"sharpen_9000"}]}"#)
            .unwrap_err();
        assert!(matches!(err, EngineError::UnknownOperation(op) if op == "sharpen_9000"));
    }

    #[test]
    fn bad_param_type_is_an_error() {
        let err = Pipeline::from_json(
            r#"{"version":1,"operations":[{"op":"exposure","params":{"amount":"lots"}}]}"#,
        )
        .unwrap_err();
        assert!(matches!(err, EngineError::InvalidPipeline(_)));
    }

    #[test]
    fn unsupported_version_is_an_error() {
        let err = Pipeline::from_json(r#"{"version":99,"operations":[]}"#).unwrap_err();
        assert!(matches!(err, EngineError::UnsupportedVersion(99)));
    }

    #[test]
    fn mask_strength_without_mask_is_an_error() {
        let err = Pipeline::from_json(
            r#"{"version":2,"operations":[{"op":"exposure","params":{"amount":0.2},"maskStrength":0.5}]}"#,
        )
        .unwrap_err();
        assert!(matches!(err, EngineError::InvalidPipeline(msg) if msg.contains("maskStrength")));
    }

    #[test]
    fn parses_dodge_burn_and_mask_strength() {
        let json = r#"{
            "version": 2,
            "operations": [
                {
                    "op": "dodge_burn",
                    "params": { "amount": 0.35, "range": "midtones" },
                    "mask": "dress",
                    "maskStrength": 0.85
                }
            ]
        }"#;
        let p = Pipeline::from_json(json).unwrap();
        assert_eq!(p.len(), 1);
        assert!((p.operations[0].mask_strength - 0.85).abs() < 1e-6);
    }

    #[test]
    fn parses_shadows_highlights_and_mask() {
        let json = r#"{
            "version": 2,
            "operations": [
                {
                    "op": "shadows_highlights",
                    "params": { "shadows": 0.4, "highlights": -0.3 },
                    "mask": "sky",
                    "maskStrength": 0.7
                }
            ]
        }"#;
        let p = Pipeline::from_json(json).unwrap();
        assert_eq!(p.len(), 1);
        assert_eq!(p.operations[0].mask.as_deref(), Some("sky"));
        assert!((p.operations[0].mask_strength - 0.7).abs() < 1e-6);
        assert!(matches!(
            p.operations[0].op,
            Operation::ShadowsHighlights(ref params)
                if (params.shadows - 0.4).abs() < 1e-6
                    && (params.highlights + 0.3).abs() < 1e-6
        ));
    }

    #[test]
    fn parses_version_four_parametric_mask() {
        let json = r#"{
            "version": 4,
            "masks": [{
                "id": "highlights",
                "source": "luminance_range",
                "params": { "min": 0.7, "max": 1.0, "softness": 0.1 }
            }],
            "operations": [
                { "op": "blacks_whites", "params": { "whites": -0.4 }, "mask": "highlights" }
            ]
        }"#;
        let p = Pipeline::from_json(json).unwrap();
        assert_eq!(p.len(), 1);
        assert!(p.mask_decls[0].source.is_parametric());
        assert!(matches!(p.operations[0].op, Operation::BlacksWhites(_)));
    }

    #[test]
    fn parses_hsl_mixer() {
        let json = r#"{
            "version": 1,
            "operations": [{ "op": "hsl_mixer", "params": { "green_sat": 0.4, "green_lum": -0.2 } }]
        }"#;
        let p = Pipeline::from_json(json).unwrap();
        assert!(matches!(
            p.operations[0].op,
            Operation::HslMixer(ref params)
                if (params.green_sat - 0.4).abs() < 1e-6 && (params.green_lum + 0.2).abs() < 1e-6
        ));
    }

    #[test]
    fn unknown_mask_source_is_an_error() {
        let err = Pipeline::from_json(
            r#"{"version":4,"masks":[{"id":"x","source":"magic_wand"}],"operations":[]}"#,
        )
        .unwrap_err();
        assert!(matches!(err, EngineError::InvalidPipeline(msg) if msg.contains("magic_wand")));
    }
}
