// Generated by uniffi-bindgen-react-native
#ifdef __cplusplus
#import "pixelcam-engine.h"
#endif

#ifdef RCT_NEW_ARCH_ENABLED
#import "RNPixelcamEngineSpec.h"

@interface PixelcamEngine : NSObject <NativePixelcamEngineSpec>
#else
#import <React/RCTBridgeModule.h>

@interface PixelcamEngine : NSObject <RCTBridgeModule>
#endif

@end