// Generated by uniffi-bindgen-react-native
#include "pixelcam-engine.h"
#include "generated/pixelcam_engine_ffi.hpp"

namespace pixelcamengine {
	using namespace facebook;

	uint8_t installRustCrate(jsi::Runtime &runtime, std::shared_ptr<react::CallInvoker> callInvoker) {
		NativePixelcamEngineFfi::registerModule(runtime, callInvoker);
		return true;
	}

	uint8_t cleanupRustCrate(jsi::Runtime &runtime) {
		return false;
	}
}